name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      uses: ./.github/actions/setup-environment

    - name: Build ClojureScript
      run: npm run build

    - name: Publish App
      run: npx electron-forge publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
